name: Image Build

on:
  push:
    branches: master

env:
  IMAGE_NAME: tdmproject/radar-ingestion
  IMAGE_TAG: ${{ github.run_number }}

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        if: ${{ github.ref == 'refs/heads/master' }}
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PWD }}
      -
        name: Build and push
        if: ${{ github.ref == 'refs/heads/master' }}
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${ IMAGE_NAME }:latest,${IMAGE_NAME}:${{ env.IMAGE_TAG }}
      -
        name: Image digest
        if: ${{ github.ref == 'refs/heads/master' }}
        run: echo ${{ steps.docker_build.outputs.digest }}
